language: csharp
solution: pst/pst.sln
before_install:
    - sudo apt-get install nunit-console
before_script:
    - nuget restore pst/pst.sln
after_script:
    - nunit-console pst/pst.tests/bin/Release/pst.tests.dll